name: Update SDK

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  update_sdk:
    name: Update SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3

      - name: Update submodules
